name: .NET Framework Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: ConsoleApp\ConsoleApp.sln                             # ソリューション名 (例: MyWpfApp.sln)。
      Test_Project_Path: ConsoleApp.Test\ConsoleApp.Test.csproj            # テストプロジェクトのパス (例: MyWpfApp.Tests\MyWpfApp.Tests.csproj)。
     
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # MSBuildをセットアップして、.NET Frameworkをビルド
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # 必要に応じてNuGetをセットアップ
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    # ソリューションの復元 (.NET Framework プロジェクトの NuGet パッケージを復元)
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    # ソリューションをビルド (.NET Framework)
    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # NuGetから xunit.runner.console をインストールしてテストを実行
    - name: Download and run xUnit Console Runner
      run: |
        # xunit.runner.console をNuGetからダウンロード
        nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory .
        
        # xunit.console.exe を使ってテストを実行
        ./xunit.runner.console.2.4.1/tools/net472/xunit.console.exe name: .NET Framework Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: ConsoleApp\ConsoleApp.sln                             # ソリューション名 (例: MyWpfApp.sln)。
      Test_Project_Path: ConsoleApp.Test\ConsoleApp.Test.csproj            # テストプロジェクトのパス (例: MyWpfApp.Tests\MyWpfApp.Tests.csproj)。
     
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # MSBuildをセットアップして、.NET Frameworkをビルド
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # 必要に応じてNuGetをセットアップ
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    # ソリューションの復元 (.NET Framework プロジェクトの NuGet パッケージを復元)
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    # ソリューションをビルド (.NET Framework)
    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # NuGetから xunit.runner.console をインストールしてテストを実行
    - name: Download and run xUnit Console Runner
      run: |
        # xunit.runner.console をNuGetからダウンロード
        nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory .
        
        # xunit.console.exe を使ってテストを実行
        ./xunit.runner.console.2.4.1/tools/net472/xunit.console.exe $env:Test_Project_Path\bin\$env:Configuration\ConsoleApp.Test.dll

      env:
        Configuration: ${{ matrix.configuration }}

    # アプリケーションの復元 (必要に応じて)
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
      env:
        Configuration: ${{ matrix.configuration }}

    # アプリケーションの復元 (必要に応じて)
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
